disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name

opt_in_rules:
  - empty_count
  - empty_string

excluded:
  - Pods
  - .build
  - Package.swift

line_length:
  warning: 120
  error: 200

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 60
  error: 100

large_tuple:
  warning: 3
  error: 4

nesting:
  type_level:
    warning: 2
  function_level:
    warning: 3

reporter: "xcode"
